### test GET /users
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImprIiwiaWF0IjoxNzYzMTA1NDcyLCJleHAiOjE3NjMxMDkwNzJ9.fHWnBFa1G5aey69j-TbSfzNe5_OwKce6tzrT9jEArAY
Accept: application/json

### test GET /data csv
GET http://localhost:3000/users
Accept: text/csv

### test GET /users/1
GET http://localhost:3000/users/1

### test GET /users/9 that does not exist
GET http://localhost:3000/users/9

### test POST /users
POST http://localhost:3000/users
Content-Type: application/json

{
    "forename":"Jyri",
    "surname":"Kemppainen"
}

### provem el PUT  amb el /users
PUT http://localhost:3000/users/4
Content-Type: application/json

{
    "forename":"Petri",
    "surname":"Laitinen"
}

### Provem el post
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "jk",
    "password": "Sala"
}


### Login test Esta Ok
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "jk",
  "password": "Sala"
}

### Test users esta to t be Ok
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImprIiwiaWF0IjoxNzYzNDk0MzMzLCJleHAiOjE3NjM0OTc5MzN9.gFt54ovt12_kkctC8OnQV_k3-Vy-itXVVarQg-8uopQ
Accept: application/json

### Test unauthorized sense token, per tal no .Ok
GET http://localhost:3000/users
Accept: application/json

### Test fake token error en teoria ok
GET http://localhost:3000/users
Authorization: Bearer asdasdsad.asdasdasd.123123


### Test si ho faig 6 vegades (too meny) OK
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImprIiwiaWF0IjoxNzYzNDk0MzMzLCJleHAiOjE3NjM0OTc5MzN9.gFt54ovt12_kkctC8OnQV_k3-Vy-itXVVarQg-8uopQ

###  login mal fet OK
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "jk",
  "password": "WRONG"
}

