openapi: 3.0.3

info:
  title: Login API Documentation
  version: 1.0.0
  description: OpenAPI OAD for the /login.

paths:
  /login:
    post:
      summary: User login
      description: Authenticates a user and returns access token.
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: jk
                password:
                  type: string
                  example: Sala
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                    example: jk
                  access_token:
                    type: string
                    description: token returned after successful login
                  token_type:
                    type: string
                    example: Bearer
                  expires_in:
                    type: string
                    example: 1h
        '401':
          description: Invalid username or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Login failed
